# Generated by Django 6.0 on 2025-12-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_starting', models.BooleanField(default=False)),
            ],
        ),
    ]
