# Generated by Django 6.0 on 2025-12-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stamina',
        ),
        migrations.AddField(
            model_name='player',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
